### ISSUE TITLE
For BMZ export: rename config.yml or include in rdf.yml

### ISSUE THREAD

**Issue by melisande-c** [CAREamics/careamics#269]
@FynnBe suggested that we should rename the CAREamics configuration file to something more unique than `config.yml` when exporting to the BMZ. The other option is to include the config within the bmz `rdf.yaml` file. This was first mentioned [here](https://github.com/bioimage-io/collection/issues/100#issuecomment-2471099238), as part of discussions on how to create a CAREamics compatibility CI for the BMZ.

**Comment by jdeschamps** [comment]
We could rename it to `careamics.yml` so that it would identify it also for our users when they are browsing their files. Actually I like the idea.

Including it in the `rdf` could be possible but now we have to think a little what it means for the loading. We need both config and state dict to create the `CAREamist`, and we would need to see how annoying it is to retrieve it from the rdf. Potentially not so annoying, but we need to assess that!

**Comment by melisande-c** [comment]
Yeah I think keeping the config file separate makes it a bit more flexible for copying, editing etc., and it also means less changes in the code and work for us 😅

So do you think `careamics.yml` or `careamics-config.yml`, I think just `careamics.yml` is good.

**Comment by FynnBe** [comment]
> I think just careamics.yml is good.

None of my business, but agreed! 👍😄  

You might want to consider `careamics.yaml` This is close to a personal preference though, but then there is also  
> Please use ".yaml" when possible.

-- https://yaml.org/faq.html

**Comment by jdeschamps** [comment]
I do like `careamics.yaml`!
